misa:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  # Position Controllers ---------------------------------------
  joint1_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint1
    pid:
      p: 1.0
      i: 0.1
      d: 0.01
  joint2_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint2
    pid:
      p: 1.0
      i: 0.1
      d: 0.01
  joint3_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint3
    pid:
      p: 1.0
      i: 0.1
      d: 0.01
  joint4_torque_controller:
    type: effort_controllers/JointEffortController
    joint: joint4
    pid:
      p: 1.0
      i: 0.1
      d: 0.01
