function Gr = CalcGravity(m1,m2,m3,m4,payload,q1,q2,q3)
%CALCGRAVITY
%    GR = CALCGRAVITY(M1,M2,M3,M4,PAYLOAD,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    31-Jul-2019 20:28:48

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = m4+payload;
t9 = payload.*2.0;
t10 = payload+t8;
t14 = t5.*3.12102e-1;
t11 = 1.0./t10;
t12 = payload.*t11;
t13 = t12+1.0./5.0e+1;
Gr = [m1.*t5.*(-7.64868e-1)-m3.*(t14+t2.*t3.*2.46051e-1-t5.*t7.*(3.9e+1./5.0e+2)-t2.*t4.*t6.*(3.9e+1./5.0e+2)).*9.806+t8.*(-t14+t13.*(t5.*t7+t2.*t4.*t6)-t2.*t3.*3.12102e-1+t5.*t7.*1.56051e-1+t2.*t4.*t6.*1.56051e-1).*9.806-m2.*(t5.*2.46051e-1+t2.*t3.*(3.9e+1./5.0e+2)).*9.806;m3.*(t5.*t6.*2.46051e-1+t3.*t4.*t5.*(3.9e+1./5.0e+2)).*9.806+t8.*(t6.*t14+t3.*t4.*t5.*1.56051e-1+t3.*t4.*t5.*t13).*9.806+m2.*t5.*t6.*7.64868e-1;t8.*(t13.*(t2.*t4+t5.*t6.*t7)+t2.*t4.*1.56051e-1+t5.*t6.*t7.*1.56051e-1).*(-9.806)-m3.*(t2.*t4.*(3.9e+1./5.0e+2)+t5.*t6.*t7.*(3.9e+1./5.0e+2)).*9.806;0.0];
