function CenterOfMasses = COMTest(q1,q2,q3)
%COMTEST
%    CENTEROFMASSES = COMTEST(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    15-May-2019 00:07:37

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = t2.*3.12102e-1;
t9 = t5.*3.12102e-1;
t10 = -t9;
CenterOfMasses = reshape([1.9e+1./1.25e+2,t5.*(-3.9e+1./5.0e+2),t2.*(3.9e+1./5.0e+2),t6.*(3.9e+1./5.0e+2)+2.18051e-1,t5.*(-2.46051e-1)-t2.*t3.*(3.9e+1./5.0e+2),t2.*2.46051e-1-t3.*t5.*(3.9e+1./5.0e+2),t6.*2.46051e-1+t3.*t4.*(3.9e+1./5.0e+2)+2.18051e-1,t10-t2.*t3.*2.46051e-1+t5.*t7.*(3.9e+1./5.0e+2)+t2.*t4.*t6.*(3.9e+1./5.0e+2),t8-t3.*t5.*2.46051e-1-t2.*t7.*(3.9e+1./5.0e+2)+t4.*t5.*t6.*(3.9e+1./5.0e+2),t6.*3.12102e-1+t3.*t4.*1.76051e-1+2.18051e-1,t10-t2.*t3.*3.12102e-1+t5.*t7.*1.76051e-1+t2.*t4.*t6.*1.76051e-1,t8-t3.*t5.*3.12102e-1-t2.*t7.*1.76051e-1+t4.*t5.*t6.*1.76051e-1],[3,4]);
