function EndPoints = EndPointsTest(q1,q2,q3)
%ENDPOINTSTEST
%    ENDPOINTS = ENDPOINTSTEST(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    16-Apr-2019 15:49:51

t2 = sin(q2);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = cos(q1);
t7 = t3.*t6.*3.12102e-1;
t8 = sin(q3);
t9 = t6.*3.12102e-1;
t10 = t3.*t5.*3.12102e-1;
EndPoints = reshape([1.0./1.0e1,0.0,9.7e1./1.0e2,2.56051e-1,t5.*(-1.56051e-1),t6.*1.56051e-1+9.7e1./1.0e2,t2.*(-1.56051e-1)+2.56051e-1,t5.*(-3.12102e-1)+t3.*t6.*1.56051e-1,t9+t3.*t5.*1.56051e-1+9.7e1./1.0e2,t2.*(-3.12102e-1)+t3.*t4.*1.56051e-1+2.56051e-1,t5.*(-3.12102e-1)+t7+t5.*t8.*1.56051e-1+t2.*t4.*t6.*1.56051e-1,t9+t10-t6.*t8.*1.56051e-1+t2.*t4.*t5.*1.56051e-1+9.7e1./1.0e2,t2.*(-3.12102e-1)+t3.*t4.*1.98051e-1+2.56051e-1,t5.*(-3.12102e-1)+t7+t5.*t8.*1.98051e-1+t2.*t4.*t6.*1.98051e-1,t9+t10-t6.*t8.*1.98051e-1+t2.*t4.*t5.*1.98051e-1+9.7e1./1.0e2],[3,5]);
