function TEE = FkineTest(q1,q2,q3,q4)
%FKINETEST
%    TEE = FKINETEST(Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    16-Apr-2019 15:49:51

t2 = cos(q2);
t3 = sin(q2);
t4 = sin(q4);
t5 = cos(q4);
t6 = sin(q3);
t7 = cos(q3);
t8 = sin(q1);
t9 = cos(q1);
t10 = t7.*t8;
t11 = t10-t3.*t6.*t9;
t12 = t7.*t9;
t13 = t3.*t6.*t8;
t14 = t12+t13;
TEE = reshape([t2.*t7,t6.*t8+t3.*t7.*t9,-t6.*t9+t3.*t7.*t8,0.0,-t3.*t5+t2.*t4.*t6,-t4.*t11+t2.*t5.*t9,t4.*t14+t2.*t5.*t8,0.0,t3.*t4+t2.*t5.*t6,-t5.*t11-t2.*t4.*t9,t5.*t14-t2.*t4.*t8,0.0,t3.*(-3.12102e-1)+t2.*t7.*1.98051e-1+2.56051e-1,t8.*(-3.12102e-1)+t2.*t9.*3.12102e-1+t6.*t8.*1.98051e-1+t3.*t7.*t9.*1.98051e-1,t9.*3.12102e-1+t2.*t8.*3.12102e-1-t6.*t9.*1.98051e-1+t3.*t7.*t8.*1.98051e-1+9.7e1./1.0e2,1.0],[4,4]);
