function GravComp = GravCompTest(L3x,L2y,L3y,L1z,L2z,g,m1,m2,m3,m4,q1,q2,q3,r3x,r1z)
%GRAVCOMPTEST
%    GRAVCOMP = GRAVCOMPTEST(L3X,L2Y,L3Y,L1Z,L2Z,G,M1,M2,M3,M4,Q1,Q2,Q3,R3X,R1Z)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    28-Apr-2019 18:07:27

t2 = sin(q1);
t3 = cos(q1);
t4 = L1z.*t2;
t5 = L2z.*t2;
t6 = cos(q2);
t7 = L2y.*t3.*t6;
t8 = sin(q2);
t9 = cos(q3);
t10 = sin(q3);
GravComp = [g.*m4.*(t4+t5+t7-L3x.*(t2.*t10+t3.*t8.*t9)+L3y.*t3.*t6)+g.*m3.*(t4+t5+t7)+g.*m1.*r1z.*t2+L1z.*g.*m2.*t2,-g.*m4.*(L2y.*t2.*t8+L3y.*t2.*t8+L3x.*t2.*t6.*t9)-L2y.*g.*m3.*t2.*t8,g.*m3.*r3x.*t9+L3x.*g.*m4.*(t3.*t9+t2.*t8.*t10),0.0];
