function GravComp = GravByPot(com_primary_ratio,com_secondary_ratio,g,m1,m2,m3,m4,payload,q1,q2,q3)
%GRAVBYPOT
%    GRAVCOMP = GRAVBYPOT(COM_PRIMARY_RATIO,COM_SECONDARY_RATIO,G,M1,M2,M3,M4,PAYLOAD,Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Aug-2019 23:41:07

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
t8 = m4+payload;
t12 = m4./5.0e+1;
t13 = payload.*(3.0./5.0e+1);
t9 = t2.*t4;
t10 = t5.*t7;
t11 = 1.0./t8;
t18 = t12+t13;
t19 = t5.*3.65442e-1;
t14 = t6.*t10;
t15 = t6.*t9;
t16 = t9+t14;
t17 = t10+t15;
GravComp = [g.*m3.*(t19-com_secondary_ratio.*t17.*1.8022e-1+t2.*t3.*1.82721e-1+com_primary_ratio.*t2.*t3.*1.8022e-1)-g.*m4.*(t10.*1.8022e-1+t15.*1.8022e-1-t19-t2.*t3.*3.62941e-1+t11.*t17.*t18)+g.*m2.*(t5.*1.82721e-1+com_primary_ratio.*t5.*1.82721e-1+com_secondary_ratio.*t2.*t3.*1.82721e-1)+com_secondary_ratio.*g.*m1.*t5.*1.82721e-1,-g.*m3.*(t5.*t6.*1.82721e-1+com_primary_ratio.*t5.*t6.*1.8022e-1+com_secondary_ratio.*t3.*t4.*t5.*1.8022e-1)-g.*m4.*(t5.*t6.*3.62941e-1+t3.*t4.*t5.*1.8022e-1+t3.*t4.*t5.*t11.*t18)-com_secondary_ratio.*g.*m2.*t5.*t6.*1.82721e-1,g.*m4.*(t9.*1.8022e-1+t14.*1.8022e-1+t11.*t16.*t18)+com_secondary_ratio.*g.*m3.*t16.*1.8022e-1,0.0];
