function Gr = NumGravCmp_v1(q1,q2,q3)
%NUMGRAVCMP_V1
%    GR = NUMGRAVCMP_V1(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    13-Jun-2019 03:17:30

t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = sin(q1);
t6 = sin(q2);
t7 = sin(q3);
Gr = [t5.*4.92943364196+t2.*t3.*2.6952889272-t5.*t7.*9.7591258491e-1-t2.*t4.*t6.*9.7591258491e-1;t5.*t6.*(-2.6952889272)-t3.*t4.*t5.*9.7591258491e-1;t2.*t4.*9.7591258491e-1+t5.*t6.*t7.*9.7591258491e-1;0.0];
