function Gr = Test(q1,q2,q3)
%TEST
%    GR = TEST(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 6.3.
%    12-Apr-2019 18:47:51

t2 = sin(q1);
t3 = cos(q1);
t4 = sin(q2);
t5 = cos(q2);
t6 = cos(q3);
t7 = sin(q3);
Gr = [t2.*(-2.2955882355)+t3.*t5.*1.3773529413+t2.*t7.*4.591176471e-1+t3.*t4.*t6.*4.591176471e-1;t2.*t4.*(-9.5381691185025e-1)+t2.*t5.*t6.*1.6489975491675e-1;t3.*t6.*(-1.6489975491675e-1)-t2.*t4.*t7.*1.6489975491675e-1;0.0];
