# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1387, 853)
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.SystemWidget = QtGui.QTabWidget(self.centralwidget)
        self.SystemWidget.setGeometry(QtCore.QRect(0, 0, 1101, 811))
        self.SystemWidget.setMinimumSize(QtCore.QSize(881, 811))
        self.SystemWidget.setElideMode(QtCore.Qt.ElideNone)
        self.SystemWidget.setDocumentMode(False)
        self.SystemWidget.setTabsClosable(False)
        self.SystemWidget.setObjectName(_fromUtf8("SystemWidget"))
        self.tab_control_interface = QtGui.QWidget()
        self.tab_control_interface.setObjectName(_fromUtf8("tab_control_interface"))
        self.radio_torque_control = QtGui.QRadioButton(self.tab_control_interface)
        self.radio_torque_control.setGeometry(QtCore.QRect(40, 60, 150, 22))
        self.radio_torque_control.setObjectName(_fromUtf8("radio_torque_control"))
        self.radio_position_control = QtGui.QRadioButton(self.tab_control_interface)
        self.radio_position_control.setGeometry(QtCore.QRect(230, 60, 150, 22))
        self.radio_position_control.setObjectName(_fromUtf8("radio_position_control"))
        self.radio_velocity_control = QtGui.QRadioButton(self.tab_control_interface)
        self.radio_velocity_control.setGeometry(QtCore.QRect(420, 60, 150, 22))
        self.radio_velocity_control.setObjectName(_fromUtf8("radio_velocity_control"))
        self.widget_sensor_interface = QtGui.QWidget(self.tab_control_interface)
        self.widget_sensor_interface.setGeometry(QtCore.QRect(570, 110, 520, 231))
        self.widget_sensor_interface.setObjectName(_fromUtf8("widget_sensor_interface"))
        self.line_13 = QtGui.QFrame(self.widget_sensor_interface)
        self.line_13.setGeometry(QtCore.QRect(0, 10, 20, 200))
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.label_5 = QtGui.QLabel(self.widget_sensor_interface)
        self.label_5.setGeometry(QtCore.QRect(20, 16, 110, 30))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line_14 = QtGui.QFrame(self.widget_sensor_interface)
        self.line_14.setGeometry(QtCore.QRect(450, 10, 20, 200))
        self.line_14.setFrameShape(QtGui.QFrame.VLine)
        self.line_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_14.setObjectName(_fromUtf8("line_14"))
        self.line_15 = QtGui.QFrame(self.widget_sensor_interface)
        self.line_15.setGeometry(QtCore.QRect(10, 6, 450, 10))
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.table_sensors = QtGui.QTableWidget(self.widget_sensor_interface)
        self.table_sensors.setGeometry(QtCore.QRect(20, 46, 428, 147))
        self.table_sensors.setObjectName(_fromUtf8("table_sensors"))
        self.table_sensors.setColumnCount(4)
        self.table_sensors.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.table_sensors.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_sensors.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_sensors.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_sensors.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_sensors.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_sensors.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_sensors.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_sensors.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(2, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_sensors.setItem(3, 3, item)
        self.line_16 = QtGui.QFrame(self.widget_sensor_interface)
        self.line_16.setGeometry(QtCore.QRect(10, 206, 450, 10))
        self.line_16.setFrameShape(QtGui.QFrame.HLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.widget_control_interface = QtGui.QStackedWidget(self.tab_control_interface)
        self.widget_control_interface.setGeometry(QtCore.QRect(49, 110, 501, 581))
        self.widget_control_interface.setObjectName(_fromUtf8("widget_control_interface"))
        self.control_torque = QtGui.QWidget()
        self.control_torque.setObjectName(_fromUtf8("control_torque"))
        self.line_4 = QtGui.QFrame(self.control_torque)
        self.line_4.setGeometry(QtCore.QRect(10, 216, 200, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.line_3 = QtGui.QFrame(self.control_torque)
        self.line_3.setGeometry(QtCore.QRect(10, 5, 200, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.button_reset_torques = QtGui.QPushButton(self.control_torque)
        self.button_reset_torques.setGeometry(QtCore.QRect(360, 440, 110, 40))
        self.button_reset_torques.setObjectName(_fromUtf8("button_reset_torques"))
        self.line_2 = QtGui.QFrame(self.control_torque)
        self.line_2.setGeometry(QtCore.QRect(201, 15, 20, 210))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.button_grav_cmp = QtGui.QPushButton(self.control_torque)
        self.button_grav_cmp.setGeometry(QtCore.QRect(20, 60, 181, 41))
        self.button_grav_cmp.setObjectName(_fromUtf8("button_grav_cmp"))
        self.button_imp_control = QtGui.QPushButton(self.control_torque)
        self.button_imp_control.setGeometry(QtCore.QRect(20, 120, 181, 41))
        self.button_imp_control.setObjectName(_fromUtf8("button_imp_control"))
        self.button_manual_command = QtGui.QPushButton(self.control_torque)
        self.button_manual_command.setGeometry(QtCore.QRect(21, 178, 181, 41))
        self.button_manual_command.setObjectName(_fromUtf8("button_manual_command"))
        self.line = QtGui.QFrame(self.control_torque)
        self.line.setGeometry(QtCore.QRect(0, 15, 20, 210))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.widget = QtGui.QWidget(self.control_torque)
        self.widget.setGeometry(QtCore.QRect(2, 263, 391, 161))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.line_9 = QtGui.QFrame(self.widget)
        self.line_9.setGeometry(QtCore.QRect(-15, -19, 20, 150))
        self.line_9.setFrameShape(QtGui.QFrame.VLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.line_10 = QtGui.QFrame(self.widget)
        self.line_10.setGeometry(QtCore.QRect(538, -18, 20, 150))
        self.line_10.setFrameShape(QtGui.QFrame.VLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.line_11 = QtGui.QFrame(self.widget)
        self.line_11.setGeometry(QtCore.QRect(-8, -27, 560, 20))
        self.line_11.setFrameShape(QtGui.QFrame.HLine)
        self.line_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_11.setObjectName(_fromUtf8("line_11"))
        self.line_12 = QtGui.QFrame(self.widget)
        self.line_12.setGeometry(QtCore.QRect(-10, 121, 560, 20))
        self.line_12.setFrameShape(QtGui.QFrame.HLine)
        self.line_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_12.setObjectName(_fromUtf8("line_12"))
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(8, 0, 190, 20))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.table_torque_command = QtGui.QTableWidget(self.widget)
        self.table_torque_command.setGeometry(QtCore.QRect(6, 25, 376, 57))
        self.table_torque_command.setObjectName(_fromUtf8("table_torque_command"))
        self.table_torque_command.setColumnCount(4)
        self.table_torque_command.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.table_torque_command.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_torque_command.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_torque_command.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_torque_command.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_torque_command.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_torque_command.setItem(0, 0, item)
        self.table_torque_command.horizontalHeader().setCascadingSectionResizes(True)
        self.table_torque_command.horizontalHeader().setDefaultSectionSize(67)
        self.table_torque_command.horizontalHeader().setMinimumSectionSize(5)
        self.pushButton_2 = QtGui.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 90, 121, 31))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_4 = QtGui.QLabel(self.control_torque)
        self.label_4.setGeometry(QtCore.QRect(20, 30, 180, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.button_move_zero_torque = QtGui.QPushButton(self.control_torque)
        self.button_move_zero_torque.setGeometry(QtCore.QRect(179, 440, 141, 40))
        self.button_move_zero_torque.setObjectName(_fromUtf8("button_move_zero_torque"))
        self.widget_control_interface.addWidget(self.control_torque)
        self.control_position = QtGui.QWidget()
        self.control_position.setObjectName(_fromUtf8("control_position"))
        self.pushButton_3 = QtGui.QPushButton(self.control_position)
        self.pushButton_3.setGeometry(QtCore.QRect(62, 160, 104, 27))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.control_position)
        self.pushButton_4.setGeometry(QtCore.QRect(295, 49, 104, 27))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.control_position)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 49, 104, 27))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.button_move_home = QtGui.QPushButton(self.control_position)
        self.button_move_home.setGeometry(QtCore.QRect(290, 510, 119, 40))
        self.button_move_home.setObjectName(_fromUtf8("button_move_home"))
        self.pushButton_7 = QtGui.QPushButton(self.control_position)
        self.pushButton_7.setGeometry(QtCore.QRect(177, 160, 104, 27))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.line_17 = QtGui.QFrame(self.control_position)
        self.line_17.setGeometry(QtCore.QRect(442, 11, 39, 470))
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.line_18 = QtGui.QFrame(self.control_position)
        self.line_18.setGeometry(QtCore.QRect(30, 10, 39, 471))
        self.line_18.setFrameShape(QtGui.QFrame.VLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.label_6 = QtGui.QLabel(self.control_position)
        self.label_6.setGeometry(QtCore.QRect(290, 130, 119, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(False)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButton_8 = QtGui.QPushButton(self.control_position)
        self.pushButton_8.setGeometry(QtCore.QRect(66, 49, 104, 27))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.line_19 = QtGui.QFrame(self.control_position)
        self.line_19.setGeometry(QtCore.QRect(50, 550, 380, 20))
        self.line_19.setFrameShape(QtGui.QFrame.HLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.label_7 = QtGui.QLabel(self.control_position)
        self.label_7.setGeometry(QtCore.QRect(48, 18, 381, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Nimbus Mono L"))
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setWordWrap(False)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.line_20 = QtGui.QFrame(self.control_position)
        self.line_20.setGeometry(QtCore.QRect(50, 0, 380, 20))
        self.line_20.setFrameShape(QtGui.QFrame.HLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.label_8 = QtGui.QLabel(self.control_position)
        self.label_8.setGeometry(QtCore.QRect(80, 240, 129, 20))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.control_position)
        self.label_9.setGeometry(QtCore.QRect(111, 130, 119, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.control_position)
        self.label_10.setGeometry(QtCore.QRect(227, 240, 90, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.control_position)
        self.label_11.setGeometry(QtCore.QRect(77, 276, 10, 17))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.control_position)
        self.label_12.setGeometry(QtCore.QRect(77, 307, 16, 17))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.control_position)
        self.label_13.setGeometry(QtCore.QRect(78, 333, 10, 20))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.control_position)
        self.label_14.setGeometry(QtCore.QRect(217, 305, 16, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.control_position)
        self.label_15.setGeometry(QtCore.QRect(217, 274, 10, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.control_position)
        self.label_16.setGeometry(QtCore.QRect(218, 333, 10, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.spinbox_actual_x = QtGui.QDoubleSpinBox(self.control_position)
        self.spinbox_actual_x.setGeometry(QtCore.QRect(107, 270, 70, 27))
        self.spinbox_actual_x.setReadOnly(True)
        self.spinbox_actual_x.setDecimals(3)
        self.spinbox_actual_x.setObjectName(_fromUtf8("spinbox_actual_x"))
        self.spinbox_actual_y = QtGui.QDoubleSpinBox(self.control_position)
        self.spinbox_actual_y.setGeometry(QtCore.QRect(107, 300, 70, 27))
        self.spinbox_actual_y.setReadOnly(True)
        self.spinbox_actual_y.setDecimals(3)
        self.spinbox_actual_y.setObjectName(_fromUtf8("spinbox_actual_y"))
        self.spinbox_actual_z = QtGui.QDoubleSpinBox(self.control_position)
        self.spinbox_actual_z.setGeometry(QtCore.QRect(107, 330, 70, 27))
        self.spinbox_actual_z.setReadOnly(True)
        self.spinbox_actual_z.setDecimals(3)
        self.spinbox_actual_z.setObjectName(_fromUtf8("spinbox_actual_z"))
        self.spinbox_goal_y = QtGui.QDoubleSpinBox(self.control_position)
        self.spinbox_goal_y.setGeometry(QtCore.QRect(247, 300, 70, 27))
        self.spinbox_goal_y.setDecimals(3)
        self.spinbox_goal_y.setObjectName(_fromUtf8("spinbox_goal_y"))
        self.spinbox_goal_z = QtGui.QDoubleSpinBox(self.control_position)
        self.spinbox_goal_z.setGeometry(QtCore.QRect(247, 330, 70, 27))
        self.spinbox_goal_z.setDecimals(3)
        self.spinbox_goal_z.setObjectName(_fromUtf8("spinbox_goal_z"))
        self.spinbox_sensitivity = QtGui.QDoubleSpinBox(self.control_position)
        self.spinbox_sensitivity.setGeometry(QtCore.QRect(308, 160, 80, 27))
        self.spinbox_sensitivity.setDecimals(4)
        self.spinbox_sensitivity.setMaximum(0.1)
        self.spinbox_sensitivity.setSingleStep(0.005)
        self.spinbox_sensitivity.setProperty("value", 0.005)
        self.spinbox_sensitivity.setObjectName(_fromUtf8("spinbox_sensitivity"))
        self.spinbox_goal_x = QtGui.QDoubleSpinBox(self.control_position)
        self.spinbox_goal_x.setGeometry(QtCore.QRect(247, 270, 70, 27))
        self.spinbox_goal_x.setDecimals(3)
        self.spinbox_goal_x.setObjectName(_fromUtf8("spinbox_goal_x"))
        self.label_17 = QtGui.QLabel(self.control_position)
        self.label_17.setGeometry(QtCore.QRect(370, 240, 50, 20))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.spinbox_err_z = QtGui.QDoubleSpinBox(self.control_position)
        self.spinbox_err_z.setGeometry(QtCore.QRect(360, 330, 70, 27))
        self.spinbox_err_z.setReadOnly(True)
        self.spinbox_err_z.setDecimals(3)
        self.spinbox_err_z.setObjectName(_fromUtf8("spinbox_err_z"))
        self.spinbox_err_x = QtGui.QDoubleSpinBox(self.control_position)
        self.spinbox_err_x.setGeometry(QtCore.QRect(360, 270, 70, 27))
        self.spinbox_err_x.setReadOnly(True)
        self.spinbox_err_x.setDecimals(3)
        self.spinbox_err_x.setObjectName(_fromUtf8("spinbox_err_x"))
        self.spinbox_err_y = QtGui.QDoubleSpinBox(self.control_position)
        self.spinbox_err_y.setGeometry(QtCore.QRect(360, 300, 70, 27))
        self.spinbox_err_y.setReadOnly(True)
        self.spinbox_err_y.setDecimals(3)
        self.spinbox_err_y.setObjectName(_fromUtf8("spinbox_err_y"))
        self.tableWidget = QtGui.QTableWidget(self.control_position)
        self.tableWidget.setGeometry(QtCore.QRect(60, 390, 391, 81))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tableWidget.setItem(0, 3, item)
        self.widget_control_interface.addWidget(self.control_position)
        self.control_velocity = QtGui.QWidget()
        self.control_velocity.setObjectName(_fromUtf8("control_velocity"))
        self.pushButton = QtGui.QPushButton(self.control_velocity)
        self.pushButton.setGeometry(QtCore.QRect(30, 70, 191, 61))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.widget_2 = QtGui.QWidget(self.control_velocity)
        self.widget_2.setGeometry(QtCore.QRect(20, 250, 391, 161))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.line_21 = QtGui.QFrame(self.widget_2)
        self.line_21.setGeometry(QtCore.QRect(-15, -19, 20, 150))
        self.line_21.setFrameShape(QtGui.QFrame.VLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.line_22 = QtGui.QFrame(self.widget_2)
        self.line_22.setGeometry(QtCore.QRect(538, -18, 20, 150))
        self.line_22.setFrameShape(QtGui.QFrame.VLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.line_23 = QtGui.QFrame(self.widget_2)
        self.line_23.setGeometry(QtCore.QRect(-8, -27, 560, 20))
        self.line_23.setFrameShape(QtGui.QFrame.HLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.line_24 = QtGui.QFrame(self.widget_2)
        self.line_24.setGeometry(QtCore.QRect(-10, 121, 560, 20))
        self.line_24.setFrameShape(QtGui.QFrame.HLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.label_18 = QtGui.QLabel(self.widget_2)
        self.label_18.setGeometry(QtCore.QRect(8, 0, 190, 20))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.table_velocity_command = QtGui.QTableWidget(self.widget_2)
        self.table_velocity_command.setGeometry(QtCore.QRect(6, 25, 376, 57))
        self.table_velocity_command.setObjectName(_fromUtf8("table_velocity_command"))
        self.table_velocity_command.setColumnCount(4)
        self.table_velocity_command.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.table_velocity_command.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_velocity_command.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_velocity_command.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_velocity_command.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_velocity_command.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_velocity_command.setItem(0, 0, item)
        self.table_velocity_command.horizontalHeader().setCascadingSectionResizes(True)
        self.table_velocity_command.horizontalHeader().setDefaultSectionSize(67)
        self.table_velocity_command.horizontalHeader().setMinimumSectionSize(5)
        self.pushButton_10 = QtGui.QPushButton(self.widget_2)
        self.pushButton_10.setGeometry(QtCore.QRect(260, 90, 121, 31))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.widget_control_interface.addWidget(self.control_velocity)
        self.widget_advanced_torque_control = QtGui.QStackedWidget(self.tab_control_interface)
        self.widget_advanced_torque_control.setGeometry(QtCore.QRect(570, 380, 520, 360))
        self.widget_advanced_torque_control.setObjectName(_fromUtf8("widget_advanced_torque_control"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.label_2 = QtGui.QLabel(self.page)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 221, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.line_5 = QtGui.QFrame(self.page)
        self.line_5.setGeometry(QtCore.QRect(10, 10, 3, 330))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_6 = QtGui.QFrame(self.page)
        self.line_6.setGeometry(QtCore.QRect(490, 10, 30, 330))
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_7 = QtGui.QFrame(self.page)
        self.line_7.setGeometry(QtCore.QRect(15, 340, 490, 3))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_8 = QtGui.QFrame(self.page)
        self.line_8.setGeometry(QtCore.QRect(15, 10, 490, 3))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.widget_advanced_grav_errors = QtGui.QWidget(self.page)
        self.widget_advanced_grav_errors.setGeometry(QtCore.QRect(10, 140, 481, 190))
        self.widget_advanced_grav_errors.setObjectName(_fromUtf8("widget_advanced_grav_errors"))
        self.line_28 = QtGui.QFrame(self.widget_advanced_grav_errors)
        self.line_28.setGeometry(QtCore.QRect(10, 206, 450, 10))
        self.line_28.setFrameShape(QtGui.QFrame.HLine)
        self.line_28.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_28.setObjectName(_fromUtf8("line_28"))
        self.label_20 = QtGui.QLabel(self.widget_advanced_grav_errors)
        self.label_20.setGeometry(QtCore.QRect(9, 91, 10, 17))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.spinbox_grav_cart_err_z = QtGui.QDoubleSpinBox(self.widget_advanced_grav_errors)
        self.spinbox_grav_cart_err_z.setGeometry(QtCore.QRect(49, 145, 62, 27))
        self.spinbox_grav_cart_err_z.setReadOnly(True)
        self.spinbox_grav_cart_err_z.setObjectName(_fromUtf8("spinbox_grav_cart_err_z"))
        self.label_19 = QtGui.QLabel(self.widget_advanced_grav_errors)
        self.label_19.setGeometry(QtCore.QRect(40, 60, 70, 17))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.spinbox_grav_cart_err_y = QtGui.QDoubleSpinBox(self.widget_advanced_grav_errors)
        self.spinbox_grav_cart_err_y.setGeometry(QtCore.QRect(49, 116, 62, 27))
        self.spinbox_grav_cart_err_y.setReadOnly(True)
        self.spinbox_grav_cart_err_y.setObjectName(_fromUtf8("spinbox_grav_cart_err_y"))
        self.label_21 = QtGui.QLabel(self.widget_advanced_grav_errors)
        self.label_21.setGeometry(QtCore.QRect(9, 121, 10, 17))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.widget_advanced_grav_errors)
        self.label_22.setGeometry(QtCore.QRect(9, 150, 10, 17))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.spinbox_grav_cart_err_x = QtGui.QDoubleSpinBox(self.widget_advanced_grav_errors)
        self.spinbox_grav_cart_err_x.setGeometry(QtCore.QRect(49, 86, 62, 27))
        self.spinbox_grav_cart_err_x.setReadOnly(True)
        self.spinbox_grav_cart_err_x.setObjectName(_fromUtf8("spinbox_grav_cart_err_x"))
        self.table_grav_errors = QtGui.QTableWidget(self.widget_advanced_grav_errors)
        self.table_grav_errors.setGeometry(QtCore.QRect(140, 30, 328, 147))
        self.table_grav_errors.setObjectName(_fromUtf8("table_grav_errors"))
        self.table_grav_errors.setColumnCount(3)
        self.table_grav_errors.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.table_grav_errors.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_grav_errors.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_grav_errors.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_grav_errors.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table_grav_errors.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_grav_errors.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_grav_errors.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_grav_errors.setItem(3, 2, item)
        self.label_23 = QtGui.QLabel(self.widget_advanced_grav_errors)
        self.label_23.setGeometry(QtCore.QRect(240, 10, 100, 17))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_24 = QtGui.QLabel(self.widget_advanced_grav_errors)
        self.label_24.setGeometry(QtCore.QRect(10, 4, 68, 17))
        self.label_24.setTextFormat(QtCore.Qt.AutoText)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.widget_advanced_torque_control.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.widget_advanced_torque_control.addWidget(self.page_2)
        self.SystemWidget.addTab(self.tab_control_interface, _fromUtf8(""))
        self.tab_status_interface = QtGui.QWidget()
        self.tab_status_interface.setObjectName(_fromUtf8("tab_status_interface"))
        self.table_statuses = QtGui.QTreeWidget(self.tab_status_interface)
        self.table_statuses.setGeometry(QtCore.QRect(90, 80, 831, 251))
        self.table_statuses.setAlternatingRowColors(True)
        self.table_statuses.setObjectName(_fromUtf8("table_statuses"))
        item_0 = QtGui.QTreeWidgetItem(self.table_statuses)
        item_0.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.table_statuses)
        item_0.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.table_statuses)
        item_0.setFlags(QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_errors = QtGui.QTableWidget(self.tab_status_interface)
        self.table_errors.setGeometry(QtCore.QRect(90, 450, 402, 291))
        self.table_errors.setAlternatingRowColors(False)
        self.table_errors.setShowGrid(True)
        self.table_errors.setGridStyle(QtCore.Qt.NoPen)
        self.table_errors.setObjectName(_fromUtf8("table_errors"))
        self.table_errors.setColumnCount(4)
        self.table_errors.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_errors.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_errors.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_errors.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_errors.setHorizontalHeaderItem(3, item)
        self.table_infos = QtGui.QTableWidget(self.tab_status_interface)
        self.table_infos.setGeometry(QtCore.QRect(520, 450, 402, 291))
        self.table_infos.setObjectName(_fromUtf8("table_infos"))
        self.table_infos.setColumnCount(4)
        self.table_infos.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_infos.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_infos.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_infos.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_infos.setHorizontalHeaderItem(3, item)
        self.label_25 = QtGui.QLabel(self.tab_status_interface)
        self.label_25.setGeometry(QtCore.QRect(90, 410, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.tab_status_interface)
        self.label_26.setGeometry(QtCore.QRect(520, 410, 400, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.button_show_errors = QtGui.QPushButton(self.tab_status_interface)
        self.button_show_errors.setGeometry(QtCore.QRect(140, 370, 140, 27))
        self.button_show_errors.setObjectName(_fromUtf8("button_show_errors"))
        self.button_hide_errors = QtGui.QPushButton(self.tab_status_interface)
        self.button_hide_errors.setGeometry(QtCore.QRect(300, 370, 140, 27))
        self.button_hide_errors.setObjectName(_fromUtf8("button_hide_errors"))
        self.button_show_info = QtGui.QPushButton(self.tab_status_interface)
        self.button_show_info.setGeometry(QtCore.QRect(570, 370, 140, 27))
        self.button_show_info.setObjectName(_fromUtf8("button_show_info"))
        self.button_hide_info = QtGui.QPushButton(self.tab_status_interface)
        self.button_hide_info.setGeometry(QtCore.QRect(730, 370, 140, 27))
        self.button_hide_info.setObjectName(_fromUtf8("button_hide_info"))
        self.SystemWidget.addTab(self.tab_status_interface, _fromUtf8(""))
        self.velocityControlTab = QtGui.QWidget()
        self.velocityControlTab.setObjectName(_fromUtf8("velocityControlTab"))
        self.SystemWidget.addTab(self.velocityControlTab, _fromUtf8(""))
        self.button_emergency = QtGui.QPushButton(self.centralwidget)
        self.button_emergency.setGeometry(QtCore.QRect(1133, 140, 171, 191))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.button_emergency.setFont(font)
        self.button_emergency.setObjectName(_fromUtf8("button_emergency"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1152, 411, 131, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.widget_system_light = QtGui.QWidget(self.centralwidget)
        self.widget_system_light.setGeometry(QtCore.QRect(1150, 440, 141, 30))
        self.widget_system_light.setStyleSheet(_fromUtf8("background-color: rgb(0, 170, 0);"))
        self.widget_system_light.setObjectName(_fromUtf8("widget_system_light"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1387, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.SystemWidget.setCurrentIndex(0)
        self.widget_control_interface.setCurrentIndex(1)
        QtCore.QObject.connect(self.button_grav_cmp, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_imp_control.setDisabled)
        QtCore.QObject.connect(self.button_grav_cmp, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_manual_command.setDisabled)
        QtCore.QObject.connect(self.button_grav_cmp, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_grav_cmp.setEnabled)
        QtCore.QObject.connect(self.button_imp_control, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_grav_cmp.setDisabled)
        QtCore.QObject.connect(self.button_imp_control, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_manual_command.setDisabled)
        QtCore.QObject.connect(self.button_imp_control, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_imp_control.setEnabled)
        QtCore.QObject.connect(self.button_manual_command, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_imp_control.setDisabled)
        QtCore.QObject.connect(self.button_manual_command, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_grav_cmp.setDisabled)
        QtCore.QObject.connect(self.button_manual_command, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_manual_command.setEnabled)
        QtCore.QObject.connect(self.button_manual_command, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget.setDisabled)
        QtCore.QObject.connect(self.button_imp_control, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget.setEnabled)
        QtCore.QObject.connect(self.button_grav_cmp, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget.setEnabled)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton_5.setDisabled)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton_4.setDisabled)
        QtCore.QObject.connect(self.pushButton_8, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton_8.setEnabled)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton_8.setDisabled)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton_4.setDisabled)
        QtCore.QObject.connect(self.pushButton_5, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton_5.setEnabled)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton_5.setDisabled)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton_8.setDisabled)
        QtCore.QObject.connect(self.pushButton_4, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.pushButton_4.setEnabled)
        QtCore.QObject.connect(self.radio_torque_control, QtCore.SIGNAL(_fromUtf8("clicked()")), self.widget_advanced_torque_control.show)
        QtCore.QObject.connect(self.radio_position_control, QtCore.SIGNAL(_fromUtf8("clicked()")), self.widget_advanced_torque_control.hide)
        QtCore.QObject.connect(self.radio_velocity_control, QtCore.SIGNAL(_fromUtf8("clicked()")), self.widget_advanced_torque_control.hide)
        QtCore.QObject.connect(self.button_show_errors, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_25.show)
        QtCore.QObject.connect(self.button_hide_errors, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_25.hide)
        QtCore.QObject.connect(self.button_show_info, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_26.show)
        QtCore.QObject.connect(self.button_hide_info, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_26.hide)
        QtCore.QObject.connect(self.button_hide_errors, QtCore.SIGNAL(_fromUtf8("clicked()")), self.table_errors.hide)
        QtCore.QObject.connect(self.button_show_errors, QtCore.SIGNAL(_fromUtf8("clicked()")), self.table_errors.show)
        QtCore.QObject.connect(self.button_show_info, QtCore.SIGNAL(_fromUtf8("clicked()")), self.table_infos.show)
        QtCore.QObject.connect(self.button_hide_info, QtCore.SIGNAL(_fromUtf8("clicked()")), self.table_infos.hide)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.radio_torque_control.setText(_translate("MainWindow", "Torque Control", None))
        self.radio_position_control.setText(_translate("MainWindow", "Position Control", None))
        self.radio_velocity_control.setText(_translate("MainWindow", "Velocity Control", None))
        self.label_5.setText(_translate("MainWindow", "Joint States", None))
        item = self.table_sensors.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "J1", None))
        item = self.table_sensors.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "J2", None))
        item = self.table_sensors.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "J3", None))
        item = self.table_sensors.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "J4", None))
        item = self.table_sensors.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Position", None))
        item = self.table_sensors.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Velocity", None))
        item = self.table_sensors.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Acceleration", None))
        item = self.table_sensors.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Torque", None))
        __sortingEnabled = self.table_sensors.isSortingEnabled()
        self.table_sensors.setSortingEnabled(False)
        item = self.table_sensors.item(0, 0)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(0, 1)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(0, 2)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(0, 3)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(1, 0)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(1, 1)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(1, 2)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(1, 3)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(2, 0)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(2, 1)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(2, 2)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(2, 3)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(3, 0)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(3, 1)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(3, 2)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_sensors.item(3, 3)
        item.setText(_translate("MainWindow", "NA", None))
        self.table_sensors.setSortingEnabled(__sortingEnabled)
        self.button_reset_torques.setText(_translate("MainWindow", "Reset Torques", None))
        self.button_grav_cmp.setText(_translate("MainWindow", "Gravity Compensation", None))
        self.button_imp_control.setText(_translate("MainWindow", "Impedance Control", None))
        self.button_manual_command.setText(_translate("MainWindow", "Manual Command", None))
        self.label_3.setText(_translate("MainWindow", "Manual Torque Command", None))
        item = self.table_torque_command.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Torque (N*m)", None))
        item = self.table_torque_command.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "J1", None))
        item = self.table_torque_command.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "J2", None))
        item = self.table_torque_command.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "J3", None))
        item = self.table_torque_command.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "J4", None))
        __sortingEnabled = self.table_torque_command.isSortingEnabled()
        self.table_torque_command.setSortingEnabled(False)
        self.table_torque_command.setSortingEnabled(__sortingEnabled)
        self.pushButton_2.setText(_translate("MainWindow", "Send Command", None))
        self.label_4.setText(_translate("MainWindow", "Control Modes", None))
        self.button_move_zero_torque.setText(_translate("MainWindow", "Move Zero Torque", None))
        self.pushButton_3.setText(_translate("MainWindow", "Increase", None))
        self.pushButton_4.setText(_translate("MainWindow", "Z", None))
        self.pushButton_5.setText(_translate("MainWindow", "Y", None))
        self.button_move_home.setText(_translate("MainWindow", "Move Home", None))
        self.pushButton_7.setText(_translate("MainWindow", "Decrease", None))
        self.label_6.setText(_translate("MainWindow", "Sensitivity(m)", None))
        self.pushButton_8.setText(_translate("MainWindow", "X", None))
        self.label_7.setText(_translate("MainWindow", "Axis", None))
        self.label_8.setText(_translate("MainWindow", "Actual Position", None))
        self.label_9.setText(_translate("MainWindow", "Position", None))
        self.label_10.setText(_translate("MainWindow", "Goal Position", None))
        self.label_11.setText(_translate("MainWindow", "X", None))
        self.label_12.setText(_translate("MainWindow", "Y", None))
        self.label_13.setText(_translate("MainWindow", "Z", None))
        self.label_14.setText(_translate("MainWindow", "Y", None))
        self.label_15.setText(_translate("MainWindow", "X", None))
        self.label_16.setText(_translate("MainWindow", "Z", None))
        self.label_17.setText(_translate("MainWindow", "Error", None))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Goal Position", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "J1", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "J2", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "J3", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "J4", None))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "Connect Haptic Device", None))
        self.label_18.setText(_translate("MainWindow", "Manual Velocity Command", None))
        item = self.table_velocity_command.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Torque (N*m)", None))
        item = self.table_velocity_command.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "J1", None))
        item = self.table_velocity_command.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "J2", None))
        item = self.table_velocity_command.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "J3", None))
        item = self.table_velocity_command.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "J4", None))
        __sortingEnabled = self.table_velocity_command.isSortingEnabled()
        self.table_velocity_command.setSortingEnabled(False)
        self.table_velocity_command.setSortingEnabled(__sortingEnabled)
        self.pushButton_10.setText(_translate("MainWindow", "Send Command", None))
        self.label_2.setText(_translate("MainWindow", "Advanced Gravity Compensation", None))
        self.label_20.setText(_translate("MainWindow", "X", None))
        self.label_19.setText(_translate("MainWindow", "Cartesian", None))
        self.label_21.setText(_translate("MainWindow", "Y", None))
        self.label_22.setText(_translate("MainWindow", "Z", None))
        item = self.table_grav_errors.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "J1", None))
        item = self.table_grav_errors.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "J2", None))
        item = self.table_grav_errors.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "J3", None))
        item = self.table_grav_errors.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "J4", None))
        item = self.table_grav_errors.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Position Error", None))
        item = self.table_grav_errors.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Goal Torque", None))
        item = self.table_grav_errors.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Torque Error", None))
        __sortingEnabled = self.table_grav_errors.isSortingEnabled()
        self.table_grav_errors.setSortingEnabled(False)
        item = self.table_grav_errors.item(0, 0)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_grav_errors.item(0, 1)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_grav_errors.item(0, 2)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_grav_errors.item(1, 0)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_grav_errors.item(1, 1)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_grav_errors.item(1, 2)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_grav_errors.item(2, 0)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_grav_errors.item(2, 1)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_grav_errors.item(2, 2)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_grav_errors.item(3, 0)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_grav_errors.item(3, 1)
        item.setText(_translate("MainWindow", "NA", None))
        item = self.table_grav_errors.item(3, 2)
        item.setText(_translate("MainWindow", "NA", None))
        self.table_grav_errors.setSortingEnabled(__sortingEnabled)
        self.label_23.setText(_translate("MainWindow", "Joint by Joint", None))
        self.label_24.setText(_translate("MainWindow", "Errors", None))
        self.SystemWidget.setTabText(self.SystemWidget.indexOf(self.tab_control_interface), _translate("MainWindow", "Control Interface", None))
        self.table_statuses.headerItem().setText(0, _translate("MainWindow", "Interfaces", None))
        __sortingEnabled = self.table_statuses.isSortingEnabled()
        self.table_statuses.setSortingEnabled(False)
        self.table_statuses.topLevelItem(0).setText(0, _translate("MainWindow", "Controller Interface", None))
        self.table_statuses.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "Command Interface", None))
        self.table_statuses.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "Sensor Interface", None))
        self.table_statuses.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "Kinematics Interface", None))
        self.table_statuses.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "Visualization Interface", None))
        self.table_statuses.topLevelItem(1).setText(0, _translate("MainWindow", "Kinova API Interface", None))
        self.table_statuses.topLevelItem(2).setText(0, _translate("MainWindow", "Status Interface", None))
        self.table_statuses.setSortingEnabled(__sortingEnabled)
        item = self.table_errors.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Source", None))
        item = self.table_errors.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Error", None))
        item = self.table_errors.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Priority", None))
        item = self.table_errors.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "RISC Score", None))
        item = self.table_infos.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Source", None))
        item = self.table_infos.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Reason", None))
        item = self.table_infos.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Functional", None))
        item = self.table_infos.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Emergency", None))
        self.label_25.setText(_translate("MainWindow", "Errors", None))
        self.label_26.setText(_translate("MainWindow", "Info", None))
        self.button_show_errors.setText(_translate("MainWindow", "Show Errors", None))
        self.button_hide_errors.setText(_translate("MainWindow", "Hide Errors", None))
        self.button_show_info.setText(_translate("MainWindow", "Show Info", None))
        self.button_hide_info.setText(_translate("MainWindow", "Hide Info", None))
        self.SystemWidget.setTabText(self.SystemWidget.indexOf(self.tab_status_interface), _translate("MainWindow", "Status Interface", None))
        self.SystemWidget.setTabText(self.SystemWidget.indexOf(self.velocityControlTab), _translate("MainWindow", "Filter", None))
        self.button_emergency.setText(_translate("MainWindow", "Emergency Stop", None))
        self.label.setText(_translate("MainWindow", "System activity", None))

