# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TorqueControlGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(608, 489)
        self.button_grav_cmp = QtGui.QPushButton(Form)
        self.button_grav_cmp.setGeometry(QtCore.QRect(29, 67, 181, 41))
        self.button_grav_cmp.setObjectName(_fromUtf8("button_grav_cmp"))
        self.button_imp_control = QtGui.QPushButton(Form)
        self.button_imp_control.setGeometry(QtCore.QRect(29, 127, 181, 41))
        self.button_imp_control.setObjectName(_fromUtf8("button_imp_control"))
        self.button_reset_torques = QtGui.QPushButton(Form)
        self.button_reset_torques.setGeometry(QtCore.QRect(280, 440, 110, 40))
        self.button_reset_torques.setObjectName(_fromUtf8("button_reset_torques"))
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(29, 37, 180, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(9, 22, 20, 210))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(210, 22, 20, 210))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(19, 12, 200, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line_4 = QtGui.QFrame(Form)
        self.line_4.setGeometry(QtCore.QRect(19, 223, 200, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.button_manual_command = QtGui.QPushButton(Form)
        self.button_manual_command.setGeometry(QtCore.QRect(30, 185, 181, 41))
        self.button_manual_command.setObjectName(_fromUtf8("button_manual_command"))
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(11, 270, 391, 161))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.line_5 = QtGui.QFrame(self.widget)
        self.line_5.setGeometry(QtCore.QRect(-15, -19, 20, 150))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_7 = QtGui.QFrame(self.widget)
        self.line_7.setGeometry(QtCore.QRect(538, -18, 20, 150))
        self.line_7.setFrameShape(QtGui.QFrame.VLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.line_6 = QtGui.QFrame(self.widget)
        self.line_6.setGeometry(QtCore.QRect(-8, -27, 560, 20))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.line_8 = QtGui.QFrame(self.widget)
        self.line_8.setGeometry(QtCore.QRect(-10, 121, 560, 20))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(8, 0, 190, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.table_manual_command = QtGui.QTableWidget(self.widget)
        self.table_manual_command.setGeometry(QtCore.QRect(6, 25, 376, 57))
        self.table_manual_command.setObjectName(_fromUtf8("table_manual_command"))
        self.table_manual_command.setColumnCount(4)
        self.table_manual_command.setRowCount(1)
        item = QtGui.QTableWidgetItem()
        self.table_manual_command.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_manual_command.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_manual_command.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_manual_command.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_manual_command.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.table_manual_command.setItem(0, 0, item)
        self.table_manual_command.horizontalHeader().setCascadingSectionResizes(True)
        self.table_manual_command.horizontalHeader().setDefaultSectionSize(67)
        self.table_manual_command.horizontalHeader().setMinimumSectionSize(5)
        self.pushButton = QtGui.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(260, 90, 121, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.button_grav_cmp, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_imp_control.setDisabled)
        QtCore.QObject.connect(self.button_grav_cmp, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_grav_cmp.setEnabled)
        QtCore.QObject.connect(self.button_imp_control, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_grav_cmp.setDisabled)
        QtCore.QObject.connect(self.button_imp_control, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_imp_control.setEnabled)
        QtCore.QObject.connect(self.button_grav_cmp, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_manual_command.setDisabled)
        QtCore.QObject.connect(self.button_imp_control, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_manual_command.setDisabled)
        QtCore.QObject.connect(self.button_manual_command, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_imp_control.setDisabled)
        QtCore.QObject.connect(self.button_manual_command, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_grav_cmp.setDisabled)
        QtCore.QObject.connect(self.button_manual_command, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.button_manual_command.setEnabled)
        QtCore.QObject.connect(self.button_grav_cmp, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget.setEnabled)
        QtCore.QObject.connect(self.button_imp_control, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget.setEnabled)
        QtCore.QObject.connect(self.button_manual_command, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.widget.setDisabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.button_grav_cmp.setText(_translate("Form", "Gravity Compensation", None))
        self.button_imp_control.setText(_translate("Form", "Impedance Control", None))
        self.button_reset_torques.setText(_translate("Form", "Reset Torques", None))
        self.label.setText(_translate("Form", "Control Modes", None))
        self.button_manual_command.setText(_translate("Form", "Manual Command", None))
        self.label_2.setText(_translate("Form", "Manual Torque Command", None))
        item = self.table_manual_command.verticalHeaderItem(0)
        item.setText(_translate("Form", "Torque (N*m)", None))
        item = self.table_manual_command.horizontalHeaderItem(0)
        item.setText(_translate("Form", "J1", None))
        item = self.table_manual_command.horizontalHeaderItem(1)
        item.setText(_translate("Form", "J2", None))
        item = self.table_manual_command.horizontalHeaderItem(2)
        item.setText(_translate("Form", "J3", None))
        item = self.table_manual_command.horizontalHeaderItem(3)
        item.setText(_translate("Form", "J4", None))
        __sortingEnabled = self.table_manual_command.isSortingEnabled()
        self.table_manual_command.setSortingEnabled(False)
        self.table_manual_command.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("Form", "Send Command", None))

